#!/bin/bash

#writing a bash script to automate full deployment  for Multi-Tier Architechure    

set -e

#Create Resource Group for the MTA
az group create --name layeredAppRG --location southafricanorth



#Create a Vnet with 3 Subnets [Web, App, DataBase]
az network vnet create --name Appstack-vnet --resource-group layeredAppRG --address-prefixes 10.0.0.0/16 --subnet-name WebSubnet --subnet-prefixes 10.0.1.0/24
az network vnet subnet create --name AppSubnet --resource-group layeredAppRG --vnet-name  Appstack-vnet --address-prefixes 10.0.2.0/24
az network vnet subnet create --name DataBaseSubnet --resource-group layeredAppRG --vnet-name  Appstack-vnet --address-prefixes 10.0.3.0/24



#Provision Linux VMs in each Subnet
az vm create --name WebVM --resource-group layeredAppRG --image Ubuntu2404 --vnet-name Appstack-vnet --subnet WebSubnet --authentication-type password --admin-username webvirtual --admin-password  kinza@J2123B#2026
az vm create --name AppVM --resource-group layeredAppRG --image Ubuntu2404 --vnet-name Appstack-vnet --subnet AppSubnet --authentication-type password --admin-username appvirtual --admin-password kinza@J2123B#2026
az vm create --name DataBaseVM --resource-group layeredAppRG --image Ubuntu2204 --vnet-name Appstack-vnet --subnet DataBaseSubnet --authentication-type password --admin-username dbvirtual --admin-password  kinza@J2123B#2026



# Create NSGs for each tier to allow only necessary communications
# az network nsg create --name WebVMNSG --resource-group layeredAppRG
# az network nsg create --name AppVMNSG --resource-group layeredAppRG
# az network nsg create --name DataBaseVMNSG --resource-group layeredAppRG


#Configure Web Tier NSG Rule

#Allow Inbound [INCOMING] HTTP from the Internet
az network nsg rule create --resource-group layeredAppRG --nsg-name WebVMNSG --name Allow-HTTP-Inbound --priority 100 --direction Inbound --access Allow --protocol Tcp --source-address-prefixes Internet --source-port-ranges "*" --destination-address-prefixes 10.0.1.0/24 --destination-port-ranges 80

#Allow Inbound HTTPS from the Internet
az network nsg rule create --resource-group layeredAppRG --nsg-name WebVMNSG --name Allow-HTTPS-Inbound --priority 110 --direction Inbound --access Allow --protocol Tcp --source-address-prefixes Internet --source-port-ranges "*" --destination-address-prefixes 10.0.1.0/24 --destination-port-ranges 443

#Allow Outbound Traffic to the Application Tier on Port 8080
az network nsg rule create --resource-group layeredAppRG --nsg-name WebVMNSG --name Allow-To-AppTier --priority 100 --direction Outbound --access Allow --protocol Tcp --source-address-prefixes 10.0.1.0/24 --source-port-ranges "*" --destination-address-prefixes 10.0.2.0/24 --destination-port-ranges 8080

#Deny Outbound Traffic to the DataBase Tier
az network nsg rule create --resource-group layeredAppRG --nsg-name WebVMNSG --name Deny-To-DBTier --priority 200 --direction Outbound --access Deny --protocol "*" --source-address-prefixes 10.0.1.0/24 --source-port-ranges "*" --destination-address-prefixes 10.0.3.0/24 --destination-port-ranges "*"




#Configure Application Tier NSG Rule

#Allow Inbound from Web Tier on Port 8080
az network nsg rule create --resource-group layeredAppRG --nsg-name AppVMNSG --name Allow-From-WebTier --priority 100 --direction Inbound --access Allow --protocol Tcp --source-address-prefixes 10.0.1.0/24 --source-port-ranges "*" --destination-address-prefixes 10.0.2.0/24 --destination-port-ranges 8080

#Deny all other Inbound traffic from Vnet
az network nsg rule create --resource-group layeredAppRG --nsg-name AppVMNSG --name Deny-All-Other-Inbound --priority 4000 --direction Inbound --access Deny --protocol "*" --source-address-prefixes VirtualNetwork --source-port-ranges "*" --destination-address-prefixes 10.0.2.0/24 --destination-port-ranges "*"

#Allow Outbound to DataBase Tier on SQL Port
az network nsg rule create --resource-group layeredAppRG --nsg-name APPVMNSG --name Allow-To-DBTier --priority 100 --direction Outbound --access Allow --protocol Tcp --source-address-prefixes 10.0.2.0/24 --source-port-ranges "*" --destination-address-prefixes 10.0.3.0/24 --destination-port-ranges 1433

#Deny Outbound to Web Tier
az network nsg rule create --resource-group layeredAppRG --nsg-name AppVMNSG --name Deny-To-WebTier --priority 200 --direction Outbound --access Deny --protocol Tcp --source-address-prefixes 10.0.2.0/24 --source-port-ranges "*" --destination-address-prefixes 10.0.1.0/24 --destination-port-ranges "*"



#Configure the DataBase Tier NSG Rule

#Allow Inbound from App Tier on SQL PORT only
az network nsg rule create --resource-group layeredAppRG --nsg-name DataBaseVMNSG --name Allow-From-AppTier --priority 100 --direction Inbound --access Allow --protocol Tcp --source-address-prefixes 10.0.2.0/24 --source-port-ranges "*" --destination-address-prefixes 10.0.3.0/24 --destination-port-ranges 1433

#Deny all other Inbound from VNET
az network nsg rule create --resource-group layeredAppRG --nsg-name DataBaseVMNSG --name Deny-All-Other-Inbound --priority 4000 --direction Inbound --access Deny --protocol "*" --source-address-prefixes VirtualNetwork --source-port-ranges "*" --destination-address-prefixes 10.0.3.0/24 --destination-port-ranges "*"

#Deny all Outbound to Internet
az network nsg rule create --resource-group layeredAppRG --nsg-name DataBaseVMNSG --name Deny-Internet-Outbound --priority 100 --direction Outbound --access Deny --protocol "*" --source-address-prefixes 10.0.3.0/24 --source-port-ranges "*" --destination-address-prefixes Internet --destination-port-ranges "*"



#Associate NSGs with their respective subnets
az network vnet subnet update --resource-group layeredAppRG --vnet-name Appstack-vnet --name WebSubnet --network-security-group WebVMNSG
az network vnet subnet update --resource-group layeredAppRG --vnet-name Appstack-vnet --name AppSubnet --network-security-group AppVMNSG
az network vnet subnet update --resource-group layeredAppRG --vnet-name Appstack-vnet --name DataBaseSubnet --network-security-group DataBaseVMNSG

